### ISSUE TITLE
Can't play after selecting mpd file 

### ISSUE THREAD

**Issue by priyochatterjee08** [sannies/rtp2dash#3]
java -jar /opt/tomcat/lib/rtp2dash-1.0.2.jar 
INFO: Storing segments and player in /tmp/live385543834510735609server 
INFO: Start Receiving H264 RTP Packets on port 5003 
INFO: Start Receiving H264 RTP Packets on port 5002 
INFO: Start Receiving H264 RTP Packets on port 5001 
INFO: Start Receiving H264 RTP Packets on port 5000 
INFO: Start Receiving AAC RTP Packets on port 5005 
INFO: Start Receiving AAC RTP Packets on port 5004 
INFO: Start receiving from tracks [RtpAacStreamingTrack{port=5005}] 
INFO: Start receiving from tracks [RtpH264StreamingTrack{port=5000}] 
INFO: Start receiving from tracks [RtpH264StreamingTrack{port=5002}] 
INFO: Start receiving from tracks [RtpAacStreamingTrack{port=5004}] 
INFO: Start receiving from tracks [RtpH264StreamingTrack{port=5003}] 
INFO: Start receiving from tracks [RtpH264StreamingTrack{port=5001}] 
INFO: [id: 0x0bcdcb85] REGISTERED 
INFO: [id: 0x0bcdcb85] BIND(0.0.0.0/0.0.0.0:8080) 
Exception in thread "main" INFO: [id: 0x0bcdcb85] CLOSE() 
INFO: [id: 0x0bcdcb85] UNREGISTERED 
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:485)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1081)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:502)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:487)
	at io.netty.channel.ChannelDuplexHandler.bind(ChannelDuplexHandler.java:38)
	at io.netty.handler.logging.LoggingHandler.bind(LoggingHandler.java:240)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:502)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:487)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:904)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:198)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:348)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
INFO: Written segment of RtpAacStreamingTrack{port=5005} sequence number 1 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5004} sequence number 1 
INFO: fragment written 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
INFO: Written segment of RtpH264StreamingTrack{port=5003} sequence number 1 
INFO: fragment written 
INFO: Written segment of RtpH264StreamingTrack{port=5002} sequence number 1 
INFO: fragment written 
INFO: Written segment of RtpH264StreamingTrack{port=5001} sequence number 1 
INFO: fragment written 
INFO: Written segment of RtpH264StreamingTrack{port=5000} sequence number 1 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5004} sequence number 2 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5005} sequence number 2 
INFO: fragment written 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
INFO: Written segment of RtpAacStreamingTrack{port=5004} sequence number 3 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5005} sequence number 3 
INFO: fragment written 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
INFO: Written segment of RtpAacStreamingTrack{port=5004} sequence number 4 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5005} sequence number 4 
INFO: fragment written 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
INFO: Written segment of RtpH264StreamingTrack{port=5003} sequence number 2 
INFO: fragment written 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
INFO: Written segment of RtpH264StreamingTrack{port=5002} sequence number 2 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5004} sequence number 5 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5005} sequence number 5 
INFO: fragment written 
INFO: Written segment of RtpH264StreamingTrack{port=5001} sequence number 2 
INFO: fragment written 
INFO: Written segment of RtpH264StreamingTrack{port=5000} sequence number 2 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5004} sequence number 6 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5005} sequence number 6 
INFO: fragment written 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
INFO: Written segment of RtpAacStreamingTrack{port=5005} sequence number 7 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5004} sequence number 7 
INFO: fragment written 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
INFO: Written segment of RtpAacStreamingTrack{port=5005} sequence number 8 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5004} sequence number 8 
INFO: fragment written 
INFO: Written segment of RtpH264StreamingTrack{port=5003} sequence number 3 
INFO: fragment written 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
INFO: Written segment of RtpH264StreamingTrack{port=5002} sequence number 3 
INFO: fragment written 
INFO: Written segment of RtpH264StreamingTrack{port=5001} sequence number 3 
INFO: fragment written 
INFO: Written segment of RtpH264StreamingTrack{port=5000} sequence number 3 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5004} sequence number 9 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5005} sequence number 9 
INFO: fragment written 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
INFO: Written segment of RtpAacStreamingTrack{port=5004} sequence number 10 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5005} sequence number 10 
INFO: fragment written 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
INFO: Written segment of RtpAacStreamingTrack{port=5005} sequence number 11 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5004} sequence number 11 
INFO: fragment written 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
INFO: Written segment of RtpH264StreamingTrack{port=5003} sequence number 4 
INFO: fragment written 
INFO: Written segment of RtpH264StreamingTrack{port=5002} sequence number 4 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5005} sequence number 12 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5004} sequence number 12 
INFO: fragment written 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
INFO: Written segment of RtpH264StreamingTrack{port=5001} sequence number 4 
INFO: fragment written 
INFO: Written segment of RtpH264StreamingTrack{port=5000} sequence number 4 
INFO: fragment written 
WARNING: Received package of payload type 72 eventhough it should be of type 96. Ignoring. 
INFO: Written segment of RtpAacStreamingTrack{port=5004} sequence number 13 
INFO: fragment written 
INFO: Written segment of RtpAacStreamingTrack{port=5005} sequence number 13 
INFO: fragment written 
INFO: Socket Timeout closed RtpH264StreamingTrack 
INFO: Done receiving RTP Packets 
INFO: Picture Buffer drained 
INFO: Socket Timeout closed RtpH264StreamingTrack 
INFO: Done receiving RTP Packets 
INFO: Socket Timeout closed RtpH264StreamingTrack 
INFO: Done receiving RTP Packets 
INFO: Picture Buffer drained 
INFO: Picture Buffer drained 
INFO: Socket Timeout closed RtpAacStreamingTrack 
INFO: Done receiving RTP Packets 
INFO: Socket Timeout closed RtpAacStreamingTrack 
INFO: Done receiving RTP Packets 
INFO: Socket Timeout closed RtpH264StreamingTrack 
INFO: Done receiving RTP Packets 
INFO: Picture Buffer drained 
INFO: Finished consuming RtpAacStreamingTrack{port=5004} 
INFO: Finished consuming RtpAacStreamingTrack{port=5005} 
INFO: Finished consuming RtpH264StreamingTrack{port=5003} 
INFO: Finished consuming RtpH264StreamingTrack{port=5001} 
INFO: Finished consuming RtpH264StreamingTrack{port=5002} 
INFO: Finished consuming RtpH264StreamingTrack{port=5000} 
sandip@sandip-HP-Notebook:~$

**Comment by priyochatterjee08** [comment]
I have placed rtp2dash jar in tomcat/lib folder. when I hit http://localhost:8080/index.html, it shows The requested resource is not available. I want to know whether there is any war file to place in /webapps directory?

**Comment by sannies** [comment]
Do I ask you to do so in any way? What makes you think it should work by
dropping it in the tomcat/lib folder? There is no war file and it's not
meant to run in a servlet container context.
Read the readme!
Step 1 - Start the Server

java -jar rtp2dash-1.0.jar

That's how you start the server




Priyabrata Chatterjee <notifications@github.com> schrieb am Mi., 3. Mai
2017 um 13:33 Uhr:

**Comment by priyochatterjee08** [comment]
It works like a charm.

**Comment by priyochatterjee08** [comment]
Can I send live streaming RTP Packets from ffmpeg to this server?
